apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: www16-intranet-network-policy
  namespace: www16-intranet
spec:
  podSelector:
    {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.244.0.0/16
          - 10.96.0.0/12
          - 192.168.1.0/24
    - podSelector:
        {}
