# Default values for collabora-code.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: collabora/code
  tag: 4.0.3.1
  pullPolicy: IfNotPresent

strategy: Recreate

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9980

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  paths: ["/"]
  hosts: ["collabora.wwwx.me"]
  tls: [{hosts: ["collabora.wwwx.me"], secretName: www16-collabora-tls-secret}]

collabora:
  DONT_GEN_SSL_CERT: true
  domain: nx11865\\.your-storageshare\\.de
  extra_params: --o:ssl.termination=true --o:ssl.enable=false
  server_name: collabora\.wwwx\.me
  password: examplepass
  username: admin
  dictionaries: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru pl_PL

securitycontext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
    - MKNOD

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  scheme: HTTP
  path: /

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  scheme: HTTP
  path: /
